### PR TITLE
Display videos

### PR DESCRIPTION
**Pull request by RakshaPawar108**
Changes in this PR:

Add videos in database (more videos to be added)
Add video-context
wrap the app in context
Add fetch call to videos
Display videos on screen
Fix video card and Home page CSS

PS: will remove the console.logs in API call and functions in a later PR

**Site is responsive**
**Deploy Preview given below**

### CODE REVIEW

**Review by shristabaruah — APPROVED** [review]
- Ui looks great. 
- Code is well structured

**Review by Abhijeet43 — APPROVED** [review]
- Nice UI 
- Code is also Clean
- Suggestions: Can Increase font size a bit of search placeholder when it moves out on focus,
Watch Later Side Menu Link breaks into another line on explore page.. Try improving it

**Review by JatuFaique — APPROVED** [review]
The code looks clean and implementation is clear.
Looks good to merge.

**Comment by RakshaPawar108** [comment]
> * Nice UI
> * Code is also Clean
> * Suggestions: Can Increase font size a bit of search placeholder when it moves out on focus,
>   Watch Later Side Menu Link breaks into another line on explore page.. Try improving it

Fixed the side menu issue. Thanks for the suggestion!

**Pull request merged**
